export { navMeta as navItems } from "./navItems";
export { socials } from "./socials";
export { statesMeta as states } from "./states";
export { aboutMeMeta as aboutMe } from "./aboutMe";
export { skillsData } from "./skillsData";
export { servicesMeta as servicesData } from "./services";
export { featuredProjectsData } from "./featuredProjectsData";
export { reviewsMeta as reviewsData } from "./reviewsData";
export { reactNextData } from "./reactNextData";
export { jsData } from "./jsData";
export { uiData } from "./uiData";
export { contactMeta as contactData } from "./contactData";
