export { navItems } from "./navItems";
export { socials } from "./socials";
export { states } from "./states";
export { aboutMe } from "./aboutMe";
export { skillsData } from "./skillsData";
export { services, servicesData } from "./services";
export { featuredProjectsData } from "./featuredProjectsData";
export { reviewsData } from "./reviewsData";
export { reactNextData } from "./reactNextData";
export { jsData } from "./jsData";
export { uiData } from "./uiData";
export { contactData } from "./contactData";
